export struct SegmentData {
    x1: float, y1: float,
    x2: float, y2: float,
    x3: float, y3: float,
    x4: float, y4: float,
    radius: float,
    sweep: bool,
}

export component AppWindow inherits Window {
    no-frame: true;
    background: transparent;

    in property <[SegmentData]> segments;
    for segment in segments : Path {
        width: 100%;
        height: 100%;
        viewbox-x: 0;
        viewbox-y: 0;
        viewbox-width: root.width / 1px;
        viewbox-height: root.height / 1px;
        fill: white;
        //fill-rule: evenodd;
        stroke: white;
        stroke-width: 1px;
        MoveTo {
            x: segment.x1;
            y: segment.y1;
        }
        LineTo {
            x: segment.x2;
            y: segment.y2;
        }
        LineTo {
            x: segment.x3;
            y: segment.y3;
        }
        ArcTo {
            x: segment.x4;
            y: segment.y4;
            radius-x: segment.radius;
            radius-y: segment.radius;
            sweep: segment.sweep;
        }
        Close{}
    }
}   